version: '3.9'

services:
  rabbitmq:
    image: rabbitmq:3.11-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  ProjectEmployeeRabbitMQ:
    container_name: ProjectEmployeeRabbitMQ
    image: projectemployee
    build: .
    ports:
      - "3000:3000"
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
      - DB_CONNECTION= YOUR MONGO DB SERVER
    depends_on:
      - rabbitmq  